### ISSUE TITLE
Project does not run on Mac OS

### ISSUE THREAD

**Issue by BartVanRaemdonck** [cypress-io/cypress-realworld-app#1290]
If I do a yarn dev, I get several errors.

```
[start:react] (Use `node --trace-deprecation ...` to show where the warning was created)
[start:react] (node:38497) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[start:api:watch] /Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/ts-node/src/index.ts:820
[start:api:watch]     return new TSError(diagnosticText, diagnosticCodes);
[start:api:watch]            ^
[start:api:watch] TSError: ⨯ Unable to compile TypeScript:
[start:api:watch] backend/helpers.ts(92,50): error TS2349: This expression is not callable.
[start:api:watch]   Type 'typeof import("/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/express-unless/dist/index")' has no call signatures.
[start:api:watch] backend/helpers.ts(93,57): error TS2349: This expression is not callable.
[start:api:watch]   Type 'typeof import("/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/express-unless/dist/index")' has no call signatures.
[start:api:watch] backend/helpers.ts(94,52): error TS2349: This expression is not callable.
[start:api:watch]   Type 'typeof import("/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/express-unless/dist/index")' has no call signatures.
[start:api:watch] 
[start:api:watch]     at createTSError (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/ts-node/src/index.ts:820:12)
[start:api:watch]     at reportTSError (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/ts-node/src/index.ts:824:19)
[start:api:watch]     at getOutput (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/ts-node/src/index.ts:1014:36)
[start:api:watch]     at Object.compile (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/ts-node/src/index.ts:1322:43)
[start:api:watch]     at Module.m._compile (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/ts-node/src/index.ts:1454:30)
[start:api:watch]     at module.exports (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/default-require-extensions/js.js:7:9)
[start:api:watch]     at /Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/append-transform/index.js:64:4
[start:api:watch]     at require.extensions.<computed> (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/ts-node/src/index.ts:1458:12)
[start:api:watch]     at Object.<anonymous> (/Users/bartvanraemdonck/workspace/battle-of-the-framworks/Cypress-real-world-app/node_modules/append-transform/index.js:64:4)
[start:api:watch]     at Module.load (node:internal/modules/cjs/loader:1037:32) {
[start:api:watch]   diagnosticCodes: [ 2349, 2349, 2349 ]
[start:api:watch] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[start:api:watch] [nodemon] app crashed - waiting for file changes before starting...
[start:react] Failed to compile.
```

**Comment by Imolos** [comment]
Idk What Mac u have but I can run it on MacOS Ventura M1 Pro MacBook. 

I would recommend to try it again. 

I have NodeJS: 19.3.0 
npm: 9.2.0
Yarn: 1.22.19

try clean clone 
And if you are on ARM use the Chromium-browser skip. 

Hope it will works for u. I had few head scratches too.

**Comment by rdooh** [comment]
Similar issue here... 

M1 Pro - Ventura
node - v19.9.0
npm 9.6.3
yarn 3.3.1

Clean install with 
`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn install`
and
`yarn dev`

But I get a TS compile failure...

I've looked into some issues with `express-unless` (and `ts-node`) but so far no joy...  If anyone has further insights, I'd really love to get this thing up and running for some evaluation.
```
===============================
[start:react] Starting the development server...
[start:react] 
[start:api:watch] /Users/.../GitHub/cypress-realworld-app/node_modules/ts-node/src/index.ts:820
[start:api:watch]     return new TSError(diagnosticText, diagnosticCodes);
[start:api:watch]            ^
[start:api:watch] TSError: ⨯ Unable to compile TypeScript:
[start:api:watch] backend/helpers.ts(92,50): error TS2349: This expression is not callable.
[start:api:watch]   Type 'typeof import("/Users/.../GitHub/cypress-realworld-app/node_modules/express-unless/dist/index")' has no call signatures.
[start:api:watch] backend/helpers.ts(93,57): error TS2349: This expression is not callable.
[start:api:watch]   Type 'typeof import("/Users/.../GitHub/cypress-realworld-app/node_modules/express-unless/dist/index")' has no call signatures.
[start:api:watch] backend/helpers.ts(94,52): error TS2349: This expression is not callable.
[start:api:watch]   Type 'typeof import("/Users/.../GitHub/cypress-realworld-app/node_modules/express-unless/dist/index")' has no call signatures.
[start:api:watch] 
[start:api:watch]     at createTSError (/Users/.../GitHub/cypress-realworld-app/node_modules/ts-node/src/index.ts:820:12)
[start:api:watch]     at reportTSError (/Users/./GitHub/cypress-realworld-app/node_modules/ts-node/src/index.ts:824:19)
[start:api:watch]     at getOutput (/Users/./GitHub/cypress-realworld-app/node_modules/ts-node/src/index.ts:1014:36)
[start:api:watch]     at Object.compile (/Users/.../GitHub/cypress-realworld-app/node_modules/ts-node/src/index.ts:1322:43)
[start:api:watch]     at Module.m._compile (/Users/.../GitHub/cypress-realworld-app/node_modules/ts-node/src/index.ts:1454:30)
[start:api:watch]     at module.exports (/Users/.../GitHub/cypress-realworld-app/node_modules/default-require-extensions/js.js:7:9)
[start:api:watch]     at /Users/.../GitHub/cypress-realworld-app/node_modules/append-transform/index.js:64:4
[start:api:watch]     at require.extensions.<computed> (/Users/.../GitHub/cypress-realworld-app/node_modules/ts-node/src/index.ts:1458:12)
[start:api:watch]     at Object.<anonymous> (/Users/...GitHub/cypress-realworld-app/node_modules/append-transform/index.js:64:4)
[start:api:watch]     at Module.load (node:internal/modules/cjs/loader:1133:32) {
[start:api:watch]   diagnosticCodes: [ 2349, 2349, 2349 ]
[start:api:watch] }
[start:api:watch] [nodemon] app crashed - waiting for file changes before starting...
[start:react] Failed to compile.
[start:react] 
[start:react] ./src/containers/AppCognito.tsx
[start:react] Module not found: Can't resolve '../aws-exports' in '/Users/.../GitHub/cypress-realworld-app/src/containers'
```

**Comment by faizvasaya** [comment]
Hey @rdooh 
The application seems to be working fine with the following configurations.

`M1 Pro - Monterey`
`Node -  16.14.2`
`npm - 8.5.0`
`yarn - 1.22.19`

Clean install with
`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn install`
and
`yarn dev`

Can you try using the above version of Node?

**Comment by nagash77** [comment]
@rdooh I have seen issues using yarn 3 as well.  I would suggest using the latest version of yarn 1 and see if the issue still exists.

**Comment by MikeMcC399** [comment]
Please note the [README: Prerequisites](https://github.com/cypress-io/cypress-realworld-app#prerequisites)

### Prerequisites

The only requirement for this project is to have [Node.js](https://nodejs.org/en/) installed on your machine. Refer to the [.node-version](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.node-version) file for the exact version.

TypeScript will be added as a local dependency to the project, so no need to install it.

.node-version is set to `16.16.0`

The repository is not compatible with Node.js `18` and later versions.

**Comment by MikeMcC399** [comment]
Also it is not advisable to try to update the dependencies. They only work as-is, and with Node.js `16.16.0`.

**Comment by MikeMcC399** [comment]
@BartVanRaemdonck 

Please execute

```bash
yarn set version classic
yarn
yarn dev
```

and check that this resolves your issue.

The error `TSError: ⨯ Unable to compile TypeScript:` occurs also on Ubuntu and Windows 11 if Yarn Modern (version 2 and higher) is used, so I suspect it has nothing to do with Mac OS.

- I also submitted PR https://github.com/cypress-io/cypress-realworld-app/pull/1337 to update the documentation accordingly.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
