### ISSUE TITLE
Error upon launching with command yarn dev

### ISSUE THREAD

**Issue by lhimo** [cypress-io/cypress-realworld-app#811]
The install procedure went fine, but when I run `yarn dev` I'm getting the following error:

```
[start:api:watch]
[start:api:watch] C:\Users\leopro\Documents\cypress-realworld-app\node_modules\ts-node\src\index.ts:513
[start:api:watch]     return new TSError(diagnosticText, diagnosticCodes)
[start:api:watch]            ^
[start:api:watch] TSError: ⨯ Unable to compile TypeScript:
[start:api:watch] backend/database.ts(49,8): error TS2307: Cannot find module '../src/models' or its corresponding type declarations.
[start:api:watch] backend/database.ts(288,6): error TS2339: Property 'assign' does not exist on type 'StringChain | (CollectionChain<any> & FunctionChain<any> & ObjectChain<any> & PrimitiveChain<any> & StringChain) | ... 4 more ... | PrimitiveChain<...>'.
[start:api:watch]   Property 'assign' does not exist on type 'StringChain'.
[start:api:watch] backend/database.ts(339,79): error TS2345: Argument of type 'object | undefined' is not assignable to parameter of type 'object'.
[start:api:watch]   Type 'undefined' is not assignable to type 'object'.
[start:api:watch]
[start:api:watch]     at createTSError (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\ts-node\src\index.ts:513:12)
[start:api:watch]     at reportTSError (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\ts-node\src\index.ts:517:19)
[start:api:watch]     at getOutput (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\ts-node\src\index.ts:752:36)
[start:api:watch]     at Object.compile (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\ts-node\src\index.ts:968:32)
[start:api:watch]     at Module.m._compile (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\ts-node\src\index.ts:1056:42)
[start:api:watch]     at module.exports (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\default-require-extensions\js.js:7:9)
[start:api:watch]     at C:\Users\leopro\Documents\cypress-realworld-app\node_modules\append-transform\index.js:64:4
[start:api:watch]     at require.extensions.<computed> (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\ts-node\src\index.ts:1059:12)
[start:api:watch]     at Object.<anonymous> (C:\Users\leopro\Documents\cypress-realworld-app\node_modules\append-transform\index.js:64:4)
[start:api:watch]     at Module.load (internal/modules/cjs/loader.js:928:32)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
[start:api:watch] [nodemon] app crashed - waiting for file changes before starting...
[start:react] [HPM] Proxy created: [ '/login', '/callback', '/logout', '/checkAuth' ]  ->  http://localhost:3001
[start:react] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[start:react] i ｢wds｣: Project is running at http://192.168.1.96/
[start:react] i ｢wds｣: webpack output is served from
[start:react] i ｢wds｣: Content not from webpack is served from C:\Users\leopro\Documents\cypress-realworld-app\public
[start:react] i ｢wds｣: 404s will fallback to /
[start:react] Starting the development server...
[start:react]
[start:react] Browserslist: caniuse-lite is outdated. Please run:
[start:react] npx browserslist@latest --update-db
```

The browser opens up on `localhost:3000` but nothing happens.

After waiting a few minutes I get:

```
Failed to compile
./src/components/UserSettingsForm.tsx
Module not found: Can't resolve '../models' in 'C:\Users\leopro\Documents\cypress-realworld-app\src\components'
```

both in terminal and in the browser page.

**Comment by mrdlmssd** [comment]
Hi
I've got the same issue today after running yarn dev command to start app on the server
I run this command separately on another CLI
npx browserslist@latest --update-db
After that I started a new command line and re-runned the command 'yarn dev' and it worked for me.
![image](https://user-images.githubusercontent.com/7752338/109732461-824c3580-7bbd-11eb-8380-c1032dfa4c89.png)
![image](https://user-images.githubusercontent.com/7752338/109732515-9db74080-7bbd-11eb-8390-42ffc5312a55.png)
![image](https://user-images.githubusercontent.com/7752338/109732298-37cab900-7bbd-11eb-9842-b72181cd0fb1.png)

**Comment by lhimo** [comment]
It's not solving the issue for me

**Comment by lhimo** [comment]
Solved with latest commits
