### ISSUE TITLE
Unable to seed data from cypress task

### ISSUE THREAD

**Issue by kirann23** [cypress-io/cypress-realworld-app#815]
Hello,

Environment used : Windows 10

I started the cypress-realworld-app using : yarn dev/yarn start and a new tab with the sign in page was displayed

However, when I try to run any test, the following error is thrown

![conn](https://user-images.githubusercontent.com/79979078/109804080-dbf94200-7c47-11eb-9479-f018b9545dbe.png)

If it helps, when I yarn dev / yarn start, the following logs were shown

```
yarn dev
yarn run v1.22.10
$ yarn db:seed:dev
$ yarn predev:cognito:ci
$ yarn copy:mock:awsexports && yarn copy:mock:awsexportses5
$ cp scripts/mock-aws-exports.js src/aws-exports.js
$ cp scripts/mock-aws-exports-es5.js aws-exports-es5.js
$ ncp ./data/database-seed.json ./data/database.json
$ cross-env NODE_ENV=development concurrently yarn:start:react yarn:start:api:watch
$ nodemon --exec yarn tsnode --watch 'backend' backend/app.ts
$ react-scripts -r @cypress/instrument-cra start
[start:api:watch] [nodemon] 2.0.7
[start:api:watch] [nodemon] to restart at any time, enter `rs`
[start:api:watch] [nodemon] watching path(s): 'backend'
[start:api:watch] [nodemon] watching extensions: ts,json
[start:api:watch] [nodemon] starting `yarn tsnode backend/app.ts`
$ nyc --silent ts-node -P tsconfig.tsnode.json backend/app.ts
[start:react] [HPM] Proxy created: [ '/login', '/callback', '/logout', '/checkAuth' ]  ->  http://localhost:3001
[start:react] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[start:react] i ｢wds｣: Project is running at <hidden>
[start:react] i ｢wds｣: webpack output is served from
[start:react] i ｢wds｣: Content not from webpack is served from C:\TestFolder\cypress-realworld-app\public
[start:react] i ｢wds｣: 404s will fallback to /
[start:react] Starting the development server...
[start:react]
[start:api:watch]
[start:api:watch] C:\TestFolder\cypress-realworld-app\node_modules\ts-node\src\index.ts:513
[start:api:watch]     return new TSError(diagnosticText, diagnosticCodes)
[start:api:watch]            ^
[start:api:watch] TSError: ⨯ Unable to compile TypeScript:
[start:api:watch] backend/app.ts(64,11): error TS2769: No overload matches this call.
[start:api:watch]   The last overload gave the following error.
[start:api:watch]     Argument of type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to parameter of type 'PathParams'.
[start:api:watch]       Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is missing the following properties from type '(string | RegExp)[]': pop, push, concat, join, and 27 more
.
[start:api:watch] backend/app.ts(74,11): error TS2769: No overload matches this call.
[start:api:watch]   The last overload gave the following error.
[start:api:watch]     Argument of type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to parameter of type 'PathParams'.
[start:api:watch]       Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to type '(string | RegExp)[]'.
[start:api:watch]
[start:api:watch]     at createTSError (C:\TestFolder\cypress-realworld-app\node_modules\ts-node\src\index.ts:513:12)
[start:api:watch]     at reportTSError (C:\TestFolder\cypress-realworld-app\node_modules\ts-node\src\index.ts:517:19)
[start:api:watch]     at getOutput (C:\TestFolder\cypress-realworld-app\node_modules\ts-node\src\index.ts:752:36)
[start:api:watch]     at Object.compile (C:\TestFolder\cypress-realworld-app\node_modules\ts-node\src\index.ts:968:32)
[start:api:watch]     at Module.m._compile (C:\TestFolder\cypress-realworld-app\node_modules\ts-node\src\index.ts:1056:42)
[start:api:watch]     at module.exports (C:\TestFolder\cypress-realworld-app\node_modules\default-require-extensions\js.js:7:9)
[start:api:watch]     at C:\TestFolder\cypress-realworld-app\node_modules\append-transform\index.js:64:4
[start:api:watch]     at require.extensions.<computed> (C:\TestFolder\cypress-realworld-app\node_modules\ts-node\src\index.ts:1059:12)
[start:api:watch]     at Object.<anonymous> (C:\TestFolder\cypress-realworld-app\node_modules\append-transform\index.js:64:4)
[start:api:watch]     at Module.load (internal/modules/cjs/loader.js:928:32)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
[start:api:watch] [nodemon] app crashed - waiting for file changes before starting...
[start:react] Compiled successfully!
[start:react]
[start:react] You can now view cypress-realworld-app in the browser.
[start:react]
[start:react]   Local:            http://localhost:3000
[start:react]   On Your Network:  http://<hidden>:3000
[start:react]
[start:react] Note that the development build is not optimized.
[start:react] To create a production build, use yarn build.
```

Let me know if more logs has to be provided and the exact path where I have to find it

Thanks

**Comment by kevinold** [comment]
Unable to reproduce this in a fresh Windows 10 environment.

The error with seeding in Cypress as shown in the screenshot can happen, but is usually solved with re-running the test.

If this does not resolve the issue, please try the following:

- Update to the latest commit on the `develop`
- Run `yarn install` to ensure modules are up-to-date
- Refresh Cypress if tests fail with this error

**Comment by kirann23** [comment]
Thanks Kevin ... I followed the steps and it works now ...

Closing the issue
