### ISSUE TITLE
WARN deprecated har-validator@5.1.5: this library is no longer supported

### ISSUE THREAD

**Issue by cvjmilos** [cypress-io/cypress-realworld-app#894]
**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `C:\Users\USER\Downloads\cypress-realworld-app-develop\cypress\plugins\index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** C:\Users\USER\Downloads\cypress-realworld-app-develop\cypress\plugins\index.ts:1
import _ from "lodash";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:986:16)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at runPlugins (C:\Users\USER\AppData\Local\Cypress\Cache\7.1.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:175:15)
    at Object.<anonymous> (C:\Users\USER\AppData\Local\Cypress\Cache\7.1.0\Cypress\resources\app\packages\server\lib\plugins\child\index.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)

**Stack trace:**
```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `C:\Users\USER\Downloads\cypress-realworld-app-develop\cypress\plugins\index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (C:\Users\USER\AppData\Local\Cypress\Cache\7.1.0\Cypress\resources\app\packages\server\lib\errors.js:988:15)
    at EventEmitter.<anonymous> (C:\Users\USER\AppData\Local\Cypress\Cache\7.1.0\Cypress\resources\app\packages\server\lib\plugins\index.js:154:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Local\Cypress\Cache\7.1.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by robertguss** [comment]
The latest `develop` branch is working and should fix this issue. Closing.
